### ISSUE TITLE
乘法最多只能出81题

### ISSUE THREAD

**Issue by yinhuagang** [frankchilahe/homework-generator#1]
超过81题就会卡死。其他题型超过81题并没有问题。

**Comment by frankchilahe** [comment]
对。因为程序会生成不重复的题，对于一位数乘法只有9*9=81种可能，超过了就会因为无法生成不重复的题而进入死循环。对于其它题型，一旦题数超过枚举的最大可能不重复题数也会有同样的问题。之后会修正一下这个问题，当用户输入题数>最大可能值时，只生成最大可能的题数。

**Comment by frankchilahe** [comment]
Fixed in commit ad13a360ac75e7eae0a0b82859120459df5c4084.
